export const LOGADO_SUCCESS = 'LOGADO SUCCESS';
export const LOGADO_REQUEST = 'LOGADO REQUEST';
export const LOGADO_FAILURE = 'LOGADO FAILURE';

export const LOGIN_SUCCESS = 'LOGIN SUCCESS';
export const LOGIN_REQUEST = 'LOGIN REQUEST';
export const LOGIN_FAILURE = 'LOGIN FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
